apiVersion: v1
kind: Service
metadata:
  name: sore-admin
  namespace: petstore
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: sore-admin
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081